### PR TITLE
Fix missing 'lodash' dependency + updating out of date dependencies

### PR DESCRIPTION
**Pull request by jrcryer**

### CODE REVIEW

**Comment by lucalanca** [comment]
Thanks a million. This fixes https://github.com/lucalanca/grunt-a11y/issues/3

**Comment by jrcryer** [comment]
:+1: No problem - happy to help and Happy New Year :fireworks:

**Comment by lucalanca** [comment]
Btw, removed lodash entirely from the dependencies as it is not being used anymore. Would not remember it if it wasn't for this PR :+1:  Happy New Year :tada:

**Comment by lucalanca** [comment]
Fixes https://github.com/lucalanca/grunt-a11y/issues/11

**Pull request merged**
