### PR TITLE
Add support for viewportSize option - Fixes #4

### LINKED ISSUE #4: Include mention of viewportSize customization

### PR DESCRIPTION
**Pull request by jrcryer**

### CODE REVIEW

**Comment by lucalanca** [comment]
@jrcryer thank you for your PR. Will review and merge it tomorrow more carefully. At first glance it seams alright :+1:

**Comment by jrcryer** [comment]
Awesome - thanks for getting back to me so quickly!

**Comment by jrcryer** [comment]
bump :smile_cat:

**Comment by brunowego** [comment]
+1

**Comment by lucalanca** [comment]
Sorry to only get back to this now. This got lost on my head.

**Pull request merged**
